### PR TITLE
Check whether the number of ioids exceeds the limit and also set a higher limit

### LINKED ISSUE #315: ne30 case fails on anvil with Scorpio
@oksanaguba reported the following issue with Scorpio on Anvil,

Running an ne30 case on Anvil gives the following error,

```
37: PIO: FATAL ERROR: Aborting... An error occured, Internal error flushing data written (ensuring/waiting_for all pending data is written to disk) to file (theta-energy-round3.cam.h1.0001-01-21-72000.nc, ncid=107). Unable to query the PnetCDF library buffer usage. err=-33. Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/blues/gpfs/home/ac.onguba/acme-b5/externals/scorpio/src/clib/pio_darray_int.c: 1829)
```

The following script (from @oksanaguba ) can be used to recreate the issue,

```
#!/bin/bash -e
which=acme-b5
fol=theta-energy-round5
nn=1800

${which}/cime/scripts/create_newcase -case $fol -res ne30_ne30 -mach anvil -compiler intel -compset FC5AV1C-L
cd $fol

./xmlchange CAM_TARGET=theta-l
./xmlchange JOB_WALLCLOCK_TIME=6:00:00

if true; then
./xmlchange --file env_mach_pes.xml NTASKS_ATM=${nn}
./xmlchange --file env_mach_pes.xml NTASKS_CPL=${nn}
./xmlchange --file env_mach_pes.xml NTASKS_OCN=${nn}
./xmlchange --file env_mach_pes.xml NTASKS_WAV=${nn}
./xmlchange --file env_mach_pes.xml NTASKS_GLC=${nn}
./xmlchange --file env_mach_pes.xml NTASKS_ROF=${nn}
./xmlchange --file env_mach_pes.xml NTASKS_LND=${nn}
#do not modify these!
./xmlchange --file env_mach_pes.xml NTASKS_ICE=64
./xmlchange --file env_mach_pes.xml NTASKS_ESP=1
./xmlchange ROOTPE=0
fi

./case.setup --reset
./case.setup

uf=user_nl_cam
#first empty line

cat > $uf <<EOF

se_ftype=2
mfilt          = 1,200
nhtfrq         = 0,1
fincl2 ='U:I','V:I','T:I','PS:I'
interpolate_output    = .false.,.true.
interpolate_nlat      =  0     , 300
interpolate_nlon      =  0     , 600
interpolate_type      =  0     , 1  
interpolate_gridtype  =  0     , 2
statefreq=1
EOF
fi

./case.build
./xmlchange STOP_N=6 ; ./xmlchange STOP_OPTION=nmonths ; 
./case.submit
```

### PR DESCRIPTION
**Pull request by dqwu**
Make sure that the user gets an error when the number of ioids
exceeds the limit.

Also increase that limit from 4K to 64K to get some E3SM cases
running.

In addition to this short-term fix, a planned long-term fix would
completely get rid of this limit with some code refactoring.

Fixes #315

### CODE REVIEW

File: src/clib/pioc.c [hunk 1]
```diff
@@ -718,6 +718,17 @@ int PIOc_InitDecomp(int iosysid, int pio_type, int ndims, const int *gdimlen, in
     }
     *ioidp = pio_add_to_iodesc_list(iodesc, comm);
 
+    /* Check whether we have exceeded the maximum number of ioids (PIO_IODESC_MAX_IDS).
+     * This limit is necessary since each file uses a sparse pointer array (with a fixed
+     * size of PIO_IODESC_MAX_IDS) to look up a data buffer per ioid.
+     * FIXME: Replace the sparse array with a map or hash map to get rid of this limit
+     */
+    if (*ioidp - PIO_IODESC_START_ID + 1 > PIO_IODESC_MAX_IDS)
```
Comment (jayeshkrishna) [inline src/clib/pioc.c:726]: Ideally this error check should go in pio_add_to_iodesc_list() where the id is assigned first to the iodesc . However the function signature for pio_add_to_iodesc_list() does not return an error, so it gets tricky unless we change the function signature. What do you think, should we change the function signature or just catch the error here?

Comment (dqwu) [reply src/clib/pioc.c:726]: Since this is only a short-term fix, I think it is OK to check the error in PIOc_InitDecomp for now.

Comment (jayeshkrishna) [reply src/clib/pioc.c:726]: ok, thanks
