### PR TITLE
Handle multi-dimensional temporal variables for ADIOS type

### LINKED ISSUE #346: PIOc_put_vars does not work with ADIOS type
When we use ADIOS type to run E3SM ne4 F case on anlworkstation,
it is observed that the h1 history .nc file (converted from ADIOS BP3
format files) is different from the one generated with PnetCDF type.

time = UNLIMITED ; // (13 currently)
nbnd = 2 ;

double time_bnds(time, nbnd) ;

[PnetCDF file]
 time_bnds =
  0, 0,
  0, 0.0833333333333333,
  0.0833333333333333, 0.166666666666667,
  0.166666666666667, 0.25,
  0.25, 0.333333333333333,
  0.333333333333333, 0.416666666666667,
  0.416666666666667, 0.5,
  0.5, 0.583333333333333,
  0.583333333333333, 0.666666666666667,
  0.666666666666667, 0.75,
  0.75, 0.833333333333333,
  0.833333333333333, 0.916666666666667,
  0.916666666666667, 1 ;

[Converted file]
 time_bnds =
  0.916666666666667, 1,
  0.916666666666667, 1,
  0.916666666666667, 1,
  0.916666666666667, 1,
  0.916666666666667, 1,
  0.916666666666667, 1,
  0.916666666666667, 1,
  0.916666666666667, 1,
  0.916666666666667, 1,
  0.916666666666667, 1,
  0.916666666666667, 1,
  0.916666666666667, 1,
  0.916666666666667, 1 ;

It seems that the values for the last time step overwrite values of previous time steps.
Below is a simple example to reproduce this issue (uses 4 time steps for testing instead of original 13).

```
#include <stdio.h>
#include <mpi.h>
#include <pio.h>
#ifdef TIMING
#include <gptl.h>
#endif

#define NUM_NETCDF_FLAVORS 5
#define NDIM 2
#define DIM_LEN 2

int main(int argc, char* argv[])
{
    int my_rank;
    int ntasks;
    int format[NUM_NETCDF_FLAVORS];
    int niotasks = 4;
    int ioproc_stride = 4;
    int ioproc_start = 0;
    int dimid[NDIM];
    int iosysid;
    int ncid;
    int varid;
    PIO_Offset start[NDIM];
    PIO_Offset count[NDIM];
    double buffer[NDIM];
    char filename[NC_MAX_NAME + 1];
    int num_flavors = 0;

#ifdef TIMING
    GPTLinitialize();
#endif

    MPI_Init(&argc, &argv);

    MPI_Comm_rank(MPI_COMM_WORLD, &my_rank);
    MPI_Comm_size(MPI_COMM_WORLD, &ntasks);

    if (ntasks != 16)
    {
        if (my_rank == 0)
            fprintf(stderr, "Number of processors must be 16!\n");

        MPI_Finalize();
        return 1;
    }

    PIOc_Init_Intracomm(MPI_COMM_WORLD, niotasks, ioproc_stride, ioproc_start,
                        PIO_REARR_SUBSET, &iosysid);

#ifdef _PNETCDF
    format[num_flavors++] = PIO_IOTYPE_PNETCDF;
#endif
#ifdef _NETCDF
    format[num_flavors++] = PIO_IOTYPE_NETCDF;
#endif
#ifdef _NETCDF4
    format[num_flavors++] = PIO_IOTYPE_NETCDF4C;
    format[num_flavors++] = PIO_IOTYPE_NETCDF4P;
#endif
#ifdef _ADIOS2
    format[num_flavors++] = PIO_IOTYPE_ADIOS;
#endif

    for (int fmt = 0; fmt < num_flavors; fmt++)
    {
        sprintf(filename, "test_put_vars_%d.nc", fmt);

        PIOc_createfile(iosysid, &ncid, &(format[fmt]), filename, PIO_CLOBBER);

        PIOc_def_dim(ncid, "time", NC_UNLIMITED, &dimid[0]);

        PIOc_def_dim(ncid, "nbnd", DIM_LEN, &dimid[1]);
        PIOc_def_var(ncid, "time_bnds", PIO_DOUBLE, NDIM, dimid, &varid);
        PIOc_enddef(ncid);

        start[1] = 0;
        count[1] = 2;

        start[0] = 0;
        count[0] = 1;
        buffer[0] = 0.0;
        buffer[1] = 0.0;
        PIOc_put_vars_double(ncid, varid, start, count, NULL, buffer);

        start[0] = 1;
        count[0] = 1;
        buffer[0] = 0.0;
        buffer[1] = 0.0833333333333333;
        PIOc_put_vars_double(ncid, varid, start, count, NULL, buffer);

        start[0] = 2;
        count[0] = 1;
        buffer[0] = 0.0833333333333333;
        buffer[1] = 0.25;
        PIOc_put_vars_double(ncid, varid, start, count, NULL, buffer);

        start[0] = 3;
        count[0] = 1;
        buffer[0] = 0.25;
        buffer[1] = 0.333333333333333;
        PIOc_put_vars_double(ncid, varid, start, count, NULL, buffer);

        PIOc_closefile(ncid);
    }

    PIOc_finalize(iosysid);

    MPI_Finalize();

#ifdef TIMING
    GPTLfinalize();
#endif

    return 0;
}
```
With 4 time steps, the similar issue can be reproduced.

time = UNLIMITED ; // (4 currently)
nbnd = 2 ;

double time_bnds(time, nbnd) ;

[PnetCDF file]
 time_bnds =
  0, 0,
  0, 0.0833333333333333,
  0.0833333333333333, 0.25,
  0.25, 0.333333333333333 ;

[Converted file]
 time_bnds =
  0.25, 0.333333333333333,
  0.25, 0.333333333333333,
  0.25, 0.333333333333333,
  0.25, 0.333333333333333 ;

### PR DESCRIPTION
**Pull request by dqwu**
PIOc_put_vars() on multi-dimensional temporal variables now works
as expected with ADIOS type. The values for previous time steps
were being overwritten with values of the last time step.
    
Use snprintf instead of sprintf throughout tools/adios2pio-nm.
  
This patch is provided by Tahsin Kurc, and requires SCORPIO to
use ADIOS 2.6.0 or higher versions. Data to be written out by
PIOc_put_vars() is treated as local arrays. ADIOS 2.5.0 does
not allow for NULL as the value of the "start" parameter in
adios2_set_selection for local arrays.

Fixes #346

### CODE REVIEW

File: tools/adios2pio-nm/adios2pio-nm-lib.cxx [hunk 1]
```diff
@@ -1204,22 +1212,50 @@ int adios2_ConvertVariablePutVar(adios2::Variable<T> *v_base,
             const auto v_blocks = bpReader[0].BlocksInfo(*v_base, (const size_t)0);
             if (mpirank == 0)
             {
+                char start_varname[PIO_MAX_NAME];
+                char count_varname[PIO_MAX_NAME];
+                sprintf(start_varname, "start_id/%s", varname.c_str());
```
Comment (jayeshkrishna) [inline tools/adios2pio-nm/adios2pio-nm-lib.cxx:1217]: Can we use snprintf here instead?

File: tools/adios2pio-nm/adios2pio-nm-lib.cxx [hunk 2]
```diff
@@ -1379,201 +1421,82 @@ int adios2_ConvertVariableTimedPutVar(adios2::Variable<T> *v_base, std::vector<T
...
-            }
-        }
-        if (var.nctype == PIO_CHAR && v_dims.size() == 1)
-        {
-            /* Character array over time may have longer dimension declaration than the actual content */
-            local_array = true;
-        }
+        char start_varname[PIO_MAX_NAME];
+        char count_varname[PIO_MAX_NAME];
+        sprintf(start_varname, "start_id/%s", varname.c_str());
```
Comment (jayeshkrishna) [inline tools/adios2pio-nm/adios2pio-nm-lib.cxx:1433]: Can we use snprintf here too?

**Comment by jayeshkrishna** [comment]
@tkurc or @dqwu : Can you include some information here on why we need ADIOS 2.6.0 or higher for this fix?

File: tools/adios2pio-nm/adios2pio-nm-lib.cxx (hunk 2 above)
Comment (tkurc) [reply tools/adios2pio-nm/adios2pio-nm-lib.cxx:1433]: Shall I convert sprintf to snprintf and push the changes or would you like @dqwu to do it?

**Comment by tkurc** [comment]
This fix requires ADIOS 2.6.0 or higher. ADIOS 2.5.0 does not allow for NULL as the value of the "start" parameter in adios2_set_selection.

**Review by tkurc — APPROVED** [review]

File: tools/adios2pio-nm/adios2pio-nm-lib.cxx (hunk 2 above)
Comment (dqwu) [reply tools/adios2pio-nm/adios2pio-nm-lib.cxx:1433]: @tkurc I will make the changes.

**Comment by jayeshkrishna** [comment]
@dqwu, Can you also add a Fortran test that shows the issue into our test suite?

**Review by jayeshkrishna — APPROVED** [review]
