### PR TITLE
Fix potential integer overflow inside PIOc_write_darray_multi()

### LINKED ISSUE #289: Potential integer overflow inside PIOc_write_darray_multi()
The following code causes a segmentation fault for ultra-high
resolution E3SM F case (ne1024) runs on Cori:
```
int PIOc_write_darray_multi(int ncid, ..., int nvars, ...)
{
    ...
    int rlen;              /* Total data buffer size. */
    ...
    /* Determine total size of aggregated data (all vars/records).
     * For netcdf serial writes we collect the data on io nodes and
     * then move that data one node at a time to the io master node
     * and write (or read). The buffer size on io task 0 must be as
     * large as the largest used to accommodate this serial io
     * method.  */
    rlen = iodesc->maxiobuflen * nvars;
    ...
    /* Allocate iobuf. */
    if (rlen > 0)
    ...
}
```
When maxiobuflen is 56,623,106 and nvars is 49, rlen would be 2,774,532,194,
larger than the maximum value of a 32-bit signed integer (2,147,483,647).
Thus, rlen has an overflow value (-1,520,435,102) and iobuf will not be allocated.

To fix this overflow issue, rlen should be defined as a 64-bit integer.
In some other functions such as recv_and_write_data(), rlen has a size_t type.

This change still does not fix the issue. We also need to define (or explicitly promote
with type casting) maxiobuflen and/or nvars to 64-bit integer.

It turns out that we should change maxiobuflen to PIO_Offset (same type as llen),
since it is described as "maximum llen participating".
```
struct io_desc_t
{
   ... 
   /** Length of the iobuffer on this task for a single field on the
     * IO node. The arrays from compute nodes gathered and rearranged
     * to the io-nodes (which are sometimes collocated with compute
     * nodes), each io task contains data from the compmap of one or
     * more compute tasks in the iomap array. */
    PIO_Offset llen;

    /** Maximum llen participating. */
    int maxiobuflen;
    ...
}
```
This overflow issue needs to be fixed since ultra-high resolution E3SM cases are likely
to generate large values of maxiobuflen on an IO task.

### PR DESCRIPTION
**Pull request by dqwu**
This PR updates the data type of maxiobuflen in struct io_desc_t,
to be consistent with llen in the same struct.

It also updates the data type of a local variable (rlen) inside
PIOc_write_darray_multi() to store the multiplication of nvars
and maxiobuflen, which might be larger than INT_MAX.

The data type of a loop counter is also updated to compare
with maxiobuflen that has a new type.

Fixes #289

### CODE REVIEW

File: src/clib/pio_darray.c [hunk 1]
```diff
@@ -108,7 +108,7 @@ int PIOc_write_darray_multi(int ncid, const int *varids, int ioid, int nvars,
     iosystem_desc_t *ios;  /* Pointer to io system information. */
     file_desc_t *file;     /* Pointer to file information. */
     io_desc_t *iodesc;     /* Pointer to IO description information. */
-    int rlen;              /* Total data buffer size. */
+    size_t rlen;           /* Total data buffer size. */
```
Comment (jayeshkrishna) [inline src/clib/pio_darray.c]: In future we might need to take a deeper look at the different types and conversions used in Scorpio, AFAICT it has been used indiscriminately throughout the legacy code. For example, bget() accepts longs, PIO_Offset is a type equivalent to MPI_Offset and we also use size_t here.
