### PR TITLE
Fix a memory corruption issue for compute_counts() used by BOX rearranger

### LINKED ISSUE #323: Initdecomp fails with ne1024 pg2 runs on Cori
@crterai reported a crash with ne1024 pg2 scream dyamond runs on Cori. The stack trace is given below for reference,
```
   32: *** Error in `/global/cscratch1/sd/terai/e3sm_scratch/cori-knl/master.ne1024pg2_r0125_oRRS18to6v3.FSCREAM-HR-DYAMOND1.1536x8x16.PREQX_DYCORE_REPLAY.20200623-17/bld/e3sm.exe': free(): corrupted unsorted chunks: 0x0000000025\

5e25e0 ***

   40: *** Error in `/global/cscratch1/sd/terai/e3sm_scratch/cori-knl/master.ne1024pg2_r0125_oRRS18to6v3.FSCREAM-HR-DYAMOND1.1536x8x16.PREQX_DYCORE_REPLAY.20200623-17/bld/e3sm.exe': free(): corrupted unsorted chunks: 0x0000000024\

bd55f0 ***

   72: GPTLstop thread 0: timer for a:PIO:pio_swapm had not been started.

  104: *** Error in `/global/cscratch1/sd/terai/e3sm_scratch/cori-knl/master.ne1024pg2_r0125_oRRS18to6v3.FSCREAM-HR-DYAMOND1.1536x8x16.PREQX_DYCORE_REPLAY.20200623-17/bld/e3sm.exe': free(): corrupted unsorted chunks: 0x000000001c\

dde4e0 ***

…

   32: forrtl: error (76): Abort trap signal

….

   32: Image              PC                Routine            Line        Source             

   32: e3sm.exe           0000000003848CBE  Unknown               Unknown  Unknown

   32: e3sm.exe           000000000318D440  Unknown               Unknown  Unknown

   32: e3sm.exe           000000000381C100  Unknown               Unknown  Unknown

   32: e3sm.exe           00000000039792B1  Unknown               Unknown  Unknown

   32: e3sm.exe           000000000399AA07  Unknown               Unknown  Unknown

   32: e3sm.exe           00000000039A0F33  Unknown               Unknown  Unknown

   32: e3sm.exe           00000000039A27E1  Unknown               Unknown  Unknown

   32: e3sm.exe           0000000001FD45F7  Unknown               Unknown  Unknown

   32: e3sm.exe           0000000001FD20F3  Unknown               Unknown  Unknown

   32: e3sm.exe           0000000001FCA2C3  Unknown               Unknown  Unknown

   32: e3sm.exe           0000000001F2C1AC  piolib_mod_mp_pio         597  piolib_mod.F90

   32: e3sm.exe           0000000000573EA7  cam_grid_support_        3711  cam_grid_support.F90

   32: e3sm.exe           000000000052A808  cam_history_suppo         658  cam_history_support.F90

   32: e3sm.exe           0000000000506973  cam_history_mp_h_        4137  cam_history.F90

   32: e3sm.exe           00000000004FFA39  cam_history_mp_ws        4650  cam_history.F90

   32: e3sm.exe           00000000004EFA61  cam_comp_mp_cam_r         382  cam_comp.F90

   32: e3sm.exe           00000000004DC6F3  atm_comp_mct_mp_a         563  atm_comp_mct.F90

   32: e3sm.exe           000000000042104F  component_mod_mp_         737  component_mod.F90

   32: e3sm.exe           0000000000403F9B  cime_comp_mod_mp_        2822  cime_comp_mod.F90

   32: e3sm.exe           0000000000420CB3  MAIN__                    133  cime_driver.F90

   32: e3sm.exe           0000000000401ADE  Unknown               Unknown  Unknown

   32: e3sm.exe           0000000003971DCF  Unknown               Unknown  Unknown

   32: e3sm.exe           00000000004019CA  Unknown               Unknown  Unknown

 
```
He is working on a branch off E3SM master and his case directory is,
```
/global/cscratch1/sd/terai/E3SM_simulation/master.ne1024pg2_r0125_oRRS18to6v3.FSCREAM-HR-DYAMOND1.1536x8x16.PREQX_DYCORE_REPLAY.20200623-17
```
The run script for the case is available at 
```
/global/cfs/cdirs/e3sm/terai/run_scripts/run.ne1024pg2_scream.dyamond1.preqxDYCORE.200701.sh 
```

### LINKED ISSUE #324: pio_initdecomp free() errors with SCORPIO (works with SCORPIO_CLASIC)
standalone HOMME, on Anvil, when running with SCORPIO.  This is one of the E3SM tests cases usually run via ./create_test. 

With 1 MPI task, it seems to run.  With 4 MPI tasks, it aborts with an error (to be posted below).  With 8 MPI tasks it hangs.

Here's a simple script to run it directly:
```

#!/bin/tcsh                                                                                                                    
#                                                                                                                              
set src=~/codes/acme/components/homme
set WDIR=~/scratch1/dev
set MACH=$src/cmake/machineFiles/anvil.cmake



cd $WDIR
# load the E3SM CIME Modules                                                                                                   
set output=`$src/../../cime/scripts/Tools/get_case_env`
eval $output


rm -Rf CMakeCache.txt CMakeFiles                                                                                              
cmake -C $MACH -DPREQX_PLEV=26 -DHOMME_USE_SCORPIO=ON $src                                                                   
if ( $status ) exit


#                                                                                                                              
# test 1                                                                                                                       
#                                                                                                                              
# -n 1    seems to work                                                                                                        
# -n 4    crashes free(): invalid pointer: 0x000000000233eef0 ***                                                              
# -n 8    hangs                                                                                                                
#                                                                                                                              
#                                                                                                                              
make -j4 baroCam
cd tests/baroCamMoist
srun -c 1 -n 4 ../../test_execs/baroCam/baroCam < baroCamMoist.nl

```

### PR DESCRIPTION
**Pull request by dqwu**
Add a C unit test for box_rearrange_create() to reproduce a memory
corruption issue found in a standalone HOMME test.

Remove a line that improperly resets totalrecv in compute_counts(),
which is the cause of the memory corruption on iodesc->rindex.

Also, for zero elements in compmap, there is no need to find a
destination IO task for them. This optimization can reduce the
value of totalrecv to reduce the memory usage.

For BOX rearranger, when logging iodesc->rindex, the buffer
length is no longer iodesc->llen and it needs to be calculated.

Fixes #323, #324

### CODE REVIEW

**Comment by ndkeen** [comment]
Would it be easy to explain under what circumstances a run might encounter this error?

**Comment by dqwu** [comment]
> Would it be easy to explain under what circumstances a run might encounter this error?

It depends on the decompositions being used. So far only a standalone HOMME test encountered this error, see issue #324 for detailed steps to reproduce.

**Comment by dqwu** [comment]
@jayeshkrishna 
e3sm_developer test suite passed with this fix (some new tests in next branch have missing input files so far) on anlworkstation.

File: tests/cunit/test_rearr.c [hunk 1]
```diff
@@ -874,6 +874,98 @@ int test_box_rearrange_create_2(MPI_Comm test_comm, int my_rank)
...
+ * Test totalrecv > iodesc->llen case in compute_counts(). */
+int test_box_rearrange_create_3(MPI_Comm test_comm, int my_rank)
+{
+#define MAPLEN1 1
+    iosystem_desc_t *ios;
+    io_desc_t *iodesc;
+    io_region *ior1;
+    int maplen = MAPLEN1;
+    PIO_Offset compmap[MAPLEN1] = {0};
+    const int gdimlen[NDIM1] = {1};
```
Comment (ambrad) [inline tests/cunit/test_rearr.c:887]: I believe this syntax does not accomplish what one might think. Only `{0}` will init the whole automatic array to 0. `{1}` will set the first entry only to 1 and leave the rest undefined.

Comment (dqwu) [reply tests/cunit/test_rearr.c:887]: Thanks for pointing it out. This kind of initialization has more than 10 occurrences in test_rearr.c, which is based on the fact that NDIM1 is 1. 
```
/* For 1-D use. */
#define NDIM1 1
```
